In [2]:
total = 0 
count = 0
numbers = input("Enter a number: (<Enter Key> to quit)")
while numbers != "":
    try:
        x = float(numbers)
        count += 1
        total = total + x
    except ValueError:
        print('NOT a number! Igored..')
    numbers = input("Enter a number: (<Enter key> to quit)")
avg = total/ count
print("\n average is", avg)

Enter a number: (<Enter Key> to quit)dsfdas
NOT a number! Igored..
Enter a number: (<Enter key> to quit)


ZeroDivisionError: division by zero

In [3]:
# 2개 이상의 숫자를 입력받아 리스트에 저장하는 함수

def numbers():
    X=[]  # X에 빈 리스트를 할당합니다.
    while True:
        number = input("Enter a number(<Enter key> to quit)")
        while number != "":
            try:
                x = float(number)
                X.append(x)
            except ValueError:
                print('>>>NOT a number! Ignored..')
            number = input("Enter a number(<Enter key> to quit)")
        if len(X) > 1:
            return X
X = numbers()

print('X:', X)

Enter a number(<Enter key> to quit)123
Enter a number(<Enter key> to quit)214
Enter a number(<Enter key> to quit)21312
Enter a number(<Enter key> to quit)1
Enter a number(<Enter key> to quit)
X: [123.0, 214.0, 21312.0, 1.0]


In [4]:
print('X:', numbers())

Enter a number(<Enter key> to quit)asdf
>>>NOT a number! Ignored..
Enter a number(<Enter key> to quit)123
Enter a number(<Enter key> to quit)2
Enter a number(<Enter key> to quit)
X: [123.0, 2.0]


In [11]:
import array as arr

mylist = [1,2,3] # 이것은 파이썬 built in list 입니다.
print(type(mylist))

mylist.append('4') # mylist의 끝에 character '4'를 추가합니다.
print(type(mylist))

mylist.insert(1,5) # mylist의 두번째 자리에 5를 끼워넣습니다.
print(mylist)

myarray = arr.array("i",[1,2,3]) # 이것은 array 입니다. import array를 해야 쓸 수 있습니다. 
print(type(myarray))

# 아래 라인의 주석을 풀고 실행하면 에러가 납니다.
# myarray.append('4') #myarray의 끝에 character '4'를 추가합니다.
print(myarray)

myarray.insert(1,5)
print(myarray)

<class 'list'>
<class 'list'>
[1, 5, 2, 3, '4']
<class 'array.array'>
array('i', [1, 2, 3])
array('i', [1, 5, 2, 3])


## 3) 리스트를 활용한 시그마의 표현
___


In [27]:
total = 0.0
for i in range(len(X)):
    total = total + X[i]
mean = total/len(X)

print('sum of X:', total)

sum of X: 21650.0


In [28]:
x

20.0

In [35]:
total = 0.0

for i in range(len(X)):
    total = total + X[i]
mean = total/len(X)
print(total)

21650.0


In [24]:
X

[123.0, 214.0, 21312.0, 1.0]

In [36]:
def median(nums):
    nums.sort()
    size = len(nums)
    p = size //2
    if size % 2 == 0:
        pr = p
        pl = p - 1
        mid = float((nums[pl] + nums[pr])/2)
    else:
        mid = nums[p]
    return mid

print('X', X)
median(X)

X [123.0, 214.0, 21312.0, 1.0]


168.5

## 평균 구하는 코드

In [37]:
def means(nums):
    total = 0.0
    for i in range(len(nums)):
        total += i
    return total/len(nums)
means(X)

1.5

## 표준편차 구하는 코드

In [39]:
avg = means(X)

def std_dev(nums, avg):
    texp = 0.0
    for i in range(len(nums)):
        texp = texp + (nums[i] - avg)**2 # 각 숫자와 평균값의 차이의 제곱을 계속 더한 후
    return (texp/(len(nums)-1))**0.5

std_dev(X,avg)

12304.434552902732

## 전체 코드: main() 함수
___

- 우리가 구현하고자 하는 값은 사용자가 입력한 숫자들에 대한 평균값, 주앙ㅇ값, 표준편차 입니다.
- 우선 사용자가 입력한 숫자를 배열(리스트)로 만듭니다.
- 각 숫자의 평균값과 중앙값을 구합니다.
- 각 숫자의 표준편차를 구합니다.

In [40]:
med = median(X)
avg = means(X)
std = std_dev(X,avg)
print("당신이 입력한 숫자{}의".format(X))
print("중앙값은{}, 평균은{}, 표준편차는{}".format(med,avg,std))

당신이 입력한 숫자[1.0, 123.0, 214.0, 21312.0]의
중앙값은168.5, 평균은1.5, 표준편차는12304.434552902732


In [45]:
import numpy as np

# 아래 A와 B는 결과적으로 같은 nadrray 객체를 생성합니다.
A = np.arange(5)
B = np.array([0,1,2,3,4]) # 파이썬 리스트를 numpy ndarray로 변환

# 하지만 C는 다르다
C = np.array([0,1,2,3,'4'])

# D도 A, B와 같은 결과를 내겠지만 B의 방법을 권합니다.
D = np.ndarray((5,), np.int64, np.array([0,1,2,3,4]))

print(A)
print(type(A))
print(B)
print(type(B))
print(C)
print(type(C))
print(D)
print(type(D))

[0 1 2 3 4]
<class 'numpy.ndarray'>
[0 1 2 3 4]
<class 'numpy.ndarray'>
['0' '1' '2' '3' '4']
<class 'numpy.ndarray'>
[0 1 2 3 4]
<class 'numpy.ndarray'>


In [47]:
A = np.arange(10).reshape(2,5) # 길이 10의 1차원 행렬을 2X5 2차원 행렬로 바꿔봅니다.

print(A.shape)
print(A.ndim)
print(A.size)

(2, 5)
2
10


In [48]:
np.arange(10).shape

(10,)

In [49]:
A = np.arange(10)
print('A:', A)
B = np.arange(10).reshape(2,5)
print('B:', B)
C = np.arange(10).reshape(3,3) # 이 에러가 난다
print('C:', C)

A: [0 1 2 3 4 5 6 7 8 9]
B: [[0 1 2 3 4]
 [5 6 7 8 9]]


ValueError: cannot reshape array of size 10 into shape (3,3)

In [50]:
A = np.arange(9).reshape(3,3)
print(A)
B=A[0]
print(B)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[0 1 2]


In [52]:
print(A[0,1])
print(B[1])

1
1


In [53]:
A[:-1]

array([[0, 1, 2],
       [3, 4, 5]])

In [61]:
print(A[:,2:])
print(A[:,1:])
print(A[:,:])

[[2]
 [5]
 [8]]
[[1 2]
 [4 5]
 [7 8]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [62]:
print(A[:,-1:])
print(A[:,-2:])
print(A[:,-3:])

[[2]
 [5]
 [8]]
[[1 2]
 [4 5]
 [7 8]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [63]:
A[1,1:2]

array([4])