In [1]:
import pandas as pd
import numpy as np

from sklearn import preprocessing

/home/jaejin/anaconda3/envs/aiffel/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


In [8]:
NBA_FILE_PATH = 'datasets/NBA_player_of_the_week.csv'

nba_player_of_the_week_df = pd.read_csv(NBA_FILE_PATH)

In [10]:
nba_player_of_the_week_df.head()

Player                    Team Conference          Date Position  \
0    Jayson Tatum          Boston Celtics       East  Feb 10, 2020       SF   
1    Nikola Jokic          Denver Nuggets       West  Feb 10, 2020        C   
2    Jaylen Brown          Boston Celtics       East   Feb 3, 2020       SF   
3  Damian Lillard  Portland Trail Blazers       West   Feb 3, 2020        G   
4   Pascal Siakam         Toronto Raptors       East  Jan 27, 2020        F   

  Height  Weight  Age  Draft Year  Seasons in league     Season  Season short  \
0    6'8     208   21        2017                  2  2019-2020          2020   
1    7'0     250   25        2014                  4  2019-2020          2020   
2    6'7     220   23        2016                  3  2019-2020          2020   
3    6'3     195   29        2012                  7  2019-2020          2020   
4    6'9     230   25        2016                  3  2019-2020          2020   

           Pre-draft Team  Real_value  Height CM  Weight KG  Last Season  
0                    Duke         0.5        203         94            1  
1  KK Mega Bemax (Serbia)         0.5        213        113            1  
2              California         0.5        201         99            1  
3             Weber State         0.5        190         88            1  
4        New Mexico State         0.5        206        104            1

In [12]:
nba_player_of_the_week_df.describe()

Weight          Age   Draft Year  Seasons in league  Season short  \
count  1340.000000  1340.000000  1340.000000        1340.000000   1340.000000   
mean    224.567164    26.738060  1996.287313           5.740299   2003.156716   
std      30.798885     3.400683    11.253558           3.293421     11.470164   
min     150.000000    19.000000  1965.000000           0.000000   1980.000000   
25%     205.000000    24.000000  1987.000000           3.000000   1994.000000   
50%     220.000000    26.000000  1998.000000           5.000000   2005.000000   
75%     250.000000    29.000000  2005.000000           8.000000   2013.000000   
max     325.000000    40.000000  2018.000000          17.000000   2020.000000   

        Real_value    Height CM    Weight KG  Last Season  
count  1340.000000  1340.000000  1340.000000  1340.000000  
mean      0.686940   201.071642   101.384328     0.023881  
std       0.242007     9.367970    14.011226     0.152734  
min       0.500000   175.000000    68.000000     0.000000  
25%       0.500000   193.000000    93.000000     0.000000  
50%       0.500000   201.000000    99.000000     0.000000  
75%       1.000000   208.000000   113.000000     0.000000  
max       1.000000   229.000000   147.000000     1.000000

In [15]:
heigt_weight_age_df = nba_player_of_the_week_df[['Height CM','Weight KG','Age']]

In [16]:
heigt_weight_age_df

Height CM  Weight KG  Age
0           203         94   21
1           213        113   25
2           201         99   23
3           190         88   29
4           206        104   25
...         ...        ...  ...
1335        188         79   24
1336        206        115   20
1337        201         98   24
1338        196         85   24
1339        198         90   30

[1340 rows x 3 columns]

In [18]:
scaler = preprocessing.MinMaxScaler() # 데이터를 1과 0 사이로 바꿔주는 도구
normalized_data = scaler.fit_transform(heigt_weight_age_df)
normalized_data

array([[0.51851852, 0.32911392, 0.0952381 ],
       [0.7037037 , 0.56962025, 0.28571429],
       [0.48148148, 0.39240506, 0.19047619],
       ...,
       [0.48148148, 0.37974684, 0.23809524],
       [0.38888889, 0.21518987, 0.23809524],
       [0.42592593, 0.27848101, 0.52380952]])

In [20]:
pd.DataFrame(normalized_data, columns = ['Height', 'Weight', 'Age'])

Height    Weight       Age
0     0.518519  0.329114  0.095238
1     0.703704  0.569620  0.285714
2     0.481481  0.392405  0.190476
3     0.277778  0.253165  0.476190
4     0.574074  0.455696  0.285714
...        ...       ...       ...
1335  0.240741  0.139241  0.238095
1336  0.574074  0.594937  0.047619
1337  0.481481  0.379747  0.238095
1338  0.388889  0.215190  0.238095
1339  0.425926  0.278481  0.523810

[1340 rows x 3 columns]

In [21]:
normalized_df = pd.DataFrame(normalized_data, columns = ['Height', 'Weight', 'Age'])

In [22]:
normalized_df.describe()

Height       Weight          Age
count  1340.000000  1340.000000  1340.000000
mean      0.482808     0.422586     0.368479
std       0.173481     0.177357     0.161937
min       0.000000     0.000000     0.000000
25%       0.333333     0.316456     0.238095
50%       0.481481     0.392405     0.333333
75%       0.611111     0.569620     0.476190
max       1.000000     1.000000     1.000000

In [34]:
age = [25,49,32,35,40]
age = pd.DataFrame(age, columns=['age'])

In [35]:
age

age
0   25
1   49
2   32
3   35
4   40

In [36]:
age_normalization = scaler.fit_transform(age)

In [37]:
age_normalization

array([[0.        ],
       [1.        ],
       [0.29166667],
       [0.41666667],
       [0.625     ]])

In [40]:
salary = [25000000,
35000000,
30000000,
50000000,
35000000]
salary = pd.DataFrame(salary, columns=['salary'])

In [41]:
sal_nor = scaler.fit_transform(salary)

In [42]:
sal_nor

array([[0. ],
       [0.4],
       [0.2],
       [1. ],
       [0.4]])

## 정규화(Regularization) 개념

- L1(Lidge), L2(Ridge)

In [45]:
from sklearn.linear_model import Lasso
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from sklearn.preprocessing import PolynomialFeatures

from math import sqrt

import numpy as np
import pandas as pd

ADMISSION_FILE_PATH = 'datasets/admission_data.csv'
admission_df = pd.read_csv(ADMISSION_FILE_PATH).drop('Serial No.', axis=1)

In [46]:
admission_df.head()

GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  Research  \
0        337          118                  4  4.5   4.5  9.65         1   
1        324          107                  4  4.0   4.5  8.87         1   
2        316          104                  3  3.0   3.5  8.00         1   
3        322          110                  3  3.5   2.5  8.67         1   
4        314          103                  2  2.0   3.0  8.21         0   

   Chance of Admit   
0              0.92  
1              0.76  
2              0.72  
3              0.80  
4              0.65